apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: geoserver-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 
    http:
      paths: 
      - path: /
        backend:
          serviceName: geoserver
          servicePort: 8080
